cabal-version:      2.4
name:               site
version:            0.1.0.0
synopsis:           Personal notes site built with Hakyll

executable site
    main-is:          site.hs
    build-depends:    base >= 4.20,
                      hakyll
    ghc-options:      -threaded
    default-language: Haskell2010
